"""added socials field for user model

Revision ID: ad89cf7af375
Revises: debfe167a3c0
Create Date: 2022-10-28 12:31:02.035619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad89cf7af375'
down_revision = 'debfe167a3c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('socials', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'socials')
    # ### end Alembic commands ###
